[project]
name = "vocos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "einops>=0.8.0",
    "huggingface-hub[cli]>=0.26.2",
    "numpy>=2.1.3",
    "safetensors>=0.4.5",
    "torch>=2.5.1",
    "torchaudio>=2.5.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
